import { lstat, symlink, unlink } from "node:fs/promises";
import { hostname, userInfo } from "node:os";
import { join } from "node:path";

/**
 * The workspace guide for a coding agent someone starts by hand in the
 * workspace or in one of its app directories, whatever the tool: Claude Code,
 * Codex and the others read `AGENTS.md` (Claude Code through a `CLAUDE.md`
 * symlink; it also reads the file from every parent directory).
 *
 * Three files in `<workspace>/`:
 *
 *   AGENTS.local.md   the operator's: written once with a hint, never touched again
 *   AGENTS.md         generated: the template below, with the machine it is on
 *                     filled in, plus a "Local notes" section holding
 *                     AGENTS.local.md; rewritten on boot, `init` and every apps
 *                     sync whenever the rendering differs from the file
 *   CLAUDE.md         a symlink to AGENTS.md, made when missing
 *
 * One generated file means every tool sees the template and the operator's
 * notes together, with no import syntax (which only Claude Code has, and which
 * asks for approval when the target is outside the working directory).
 * Keep the template generic (no real app or machine names) and short: the
 * details live in the checkout's `AGENTS.md` and `docs/`, which it points at.
 * The one machine-specific part is the "This machine" section, generated from
 * the facts ai-space has: a session must know where it is running, or a skill
 * written on another machine sends it over ssh to the very host it is on.
 */

export const GUIDE_FILE = "AGENTS.md";
export const LOCAL_FILE = "AGENTS.local.md";
export const CLAUDE_FILE = "CLAUDE.md";

/** What the guide says about the machine it is generated on. */
export type Machine = {
  /** What the space calls itself (`SPACE_NAME`), the hostname when unset. */
  name: string;
  hostname: string;
  /** The user ai-space runs as. */
  user: string;
  /** The workspace directory. */
  home: string;
};

/** The machine facts for this process: `name` from `SPACE_NAME` when given. */
export function localMachine(home: string, name?: string): Machine {
  const host = hostname();
  let user = "";
  try {
    user = userInfo().username;
  } catch {
    user = process.env.USER ?? "";
  }
  return { name: name?.trim() || host, hostname: host, user, home };
}

export const LOCAL_TEMPLATE = `<!--
Local notes for this workspace: yours to edit, ai-space never rewrites this file.
Everything below is copied into the "Local notes" section of AGENTS.md on the
next boot or POST /api/apps/sync, so every agent tool that reads AGENTS.md sees
it. Put machine-specific things here: which apps matter, the other machines and
their ssh aliases, tasks not to rerun by hand. This machine's own name, user and
workspace path are already in the generated "This machine" section. HTML
comments like this one are left out.
-->
`;

export const GUIDE_HEAD = `<!-- Generated by ai-space from its template and AGENTS.local.md; rewritten on boot and on each apps sync. Do not edit: put local notes in AGENTS.local.md. -->
# AGENTS.md - ai-space workspace

You are in an ai-space workspace: one directory that holds everything a running ai-space owns on this machine. This file is for an agent operating the space (running apps, tasks, data), not for changing ai-space's own code. It is generated; the operator's own notes are in the last section and come from \`AGENTS.local.md\`.

`;

/** The section that says where the session is running. */
export function machineSection(m: Machine): string {
  return `## This machine

This is the space host \`${m.name}\` (hostname \`${m.hostname}\`, user \`${m.user}\`), and the workspace is \`${m.home}\`. Every app under \`apps/\`, its data under \`data/\`, and the API on \`127.0.0.1\` are local files and ports here: read them directly, never through \`ssh\`. A skill, prompt or app guide that tells you to ssh somewhere, to look under a home directory, or to use a path outside this workspace was written on another machine; on this one the layout below is what holds, and an app's real paths come from \`data/<app>/space.env\` or \`bun src/index.ts env <app>\` (run in \`core/\`). The other machines are the peers named in \`.env\` and whatever the operator's notes say.

`;
}

export const GUIDE_TEMPLATE = `## Layout

- \`core/\` - the ai-space checkout that runs here (when deployed by \`git push\`). Its \`AGENTS.md\` and \`docs/\` are the reference: \`docs/app-spec.md\` (what an app is, \`space.yaml\`), \`docs/scheduler.md\`, \`docs/storage.md\`, \`docs/backup.md\`, \`docs/notify.md\`, \`docs/model.md\`, \`docs/runtimes.md\`, \`docs/panel.md\`, \`docs/peers.md\`, \`docs/terminal.md\`, \`docs/install.md\`.
- \`apps/<app>/\` - one directory per app, each its own git repository with a \`space.yaml\`. Change an app inside its own directory; it usually has its own \`CLAUDE.md\` or \`AGENTS.md\`, which applies on top of this one.
- \`data/\` - runtime state: \`space.db\` (ai-space's own), then one directory per app holding its databases, \`blobs/\` and \`space.env\` (the variables ai-space hands the app).
- \`logs/\` - task run logs.
- \`.env\` - ai-space configuration and the secrets app manifests reference. \`secrets/\`, when present, holds encrypted secrets.
- \`.claude/skills/\` - links to every shared skill and every app's skills; ai-space refreshes them on boot and on each apps sync.
- \`runtimes.yaml\` - the AI runtimes this space can start (\`docs/runtimes.md\`).
- \`AGENTS.md\`, \`CLAUDE.md\` (a link to it), \`AGENTS.local.md\` - this guide, generated by ai-space, and the operator's notes it embeds.

## The running service

ai-space listens on the host and port in \`.env\` (\`SPACE_HOST\`, \`SPACE_PORT\`; default \`127.0.0.1:8700\`) as the user unit \`ai-space\`:

\`\`\`sh
curl -s http://127.0.0.1:8700/healthz
journalctl --user -u ai-space -n 50          # logs
systemctl --user restart ai-space             # after editing .env
\`\`\`

Mutating routes take \`Authorization: Bearer $SPACE_API_TOKEN\` (the token is in \`.env\`). The ones an operator reaches for:

- \`POST /api/apps/sync\` after adding, removing or editing an app's \`space.yaml\`; \`POST /api/apps/<app>/sync\` for one app.
- \`GET /api/tasks\`, \`POST /api/tasks/<id>/run\`, \`PATCH /api/tasks/<id>\` (\`{ enabled }\`), \`GET /api/tasks/<id>/runs\`.
- \`GET /api/services\` (every app's health), \`GET /api/apps?all=1\`.
- \`POST /api/notify\` to send a message; \`GET /api/notify/channels\`.
- \`GET /api/backups\`, \`POST /api/apps/<app>/backups\` to snapshot now.
- \`POST /api/model/run\`, \`GET /api/model/usage\` for model calls and their cost.

Peers (\`docs/peers.md\`): when \`.env\` lists other ai-space machines as \`SPACE_PEER_<NAME>\`, this one is a hub and \`GET /api/peers\` shows each peer's health and what its panel holds. A peer app is addressed as \`<peer>/<app>\`; through \`/api/peers/<peer>/...\` the hub can chat with the peer's agents, read their sessions, show its widgets and uninstall one of its apps, and nothing else. A peer's tasks, data, backups and files stay on that machine: reach them through that machine's own ai-space or a shell there, not through this one.

The same from the shell, run inside \`core/\`: \`bun src/index.ts env <app>\` (an app's provisioned variables), \`bun src/index.ts notify\`, \`backup <app>\`, \`backups\`, \`restore <app>\`.

## Rules

- Do not edit databases under \`data/\` by hand or with sqlite while the service runs; go through the app's own commands or the API. Restores go through \`restore\`.
- \`.env\`, \`data/*/space.env\` and \`secrets/\` hold credentials: never print them in full, paste them into a chat, or commit them anywhere.
- \`core/\` is a deployment checkout, not a place to develop: changes are made in the source repository and arrive by \`git push\`. Read it, do not edit it here.
- An app is changed in its own repository under \`apps/<app>/\` with its own commits; \`git status\` there before you start, and keep the app's \`space.yaml\` valid (\`docs/app-spec.md\`).
- A new app, or an existing project to bring in, follows the \`space-app\` skill; a message to a person goes through the \`notify\` skill.
- Ask before stopping a service, deleting an app or its data, or restarting ai-space while tasks are running.
- A skill, agent prompt or task prompt you write must work on every machine the app runs on: no hostname, IP address, ssh alias, home directory or "am I on the server" marker of its own. It takes paths from the app's environment (\`SPACE_APP_DIR\`, \`SPACE_APP_DATA_DIR\`, \`DATABASE_URL\`, \`BLOB_URL\`), the API from \`SPACE_API_URL\`, and where it is running from the "This machine" section above; a host it must reach from the operator's notes, or it asks.
- Something worth telling the next session goes in \`AGENTS.local.md\`, never in this file: it is regenerated.

## Local notes

`;

const EMPTY_LOCAL = "Nothing yet: the operator writes them in `AGENTS.local.md`.\n";

/** The guide as it should read on `machine` for the given AGENTS.local.md content. */
export function renderGuide(local: string, machine: Machine): string {
  const notes = local.replace(/<!--[\s\S]*?-->/g, "").trim();
  return GUIDE_HEAD + machineSection(machine) + GUIDE_TEMPLATE + (notes ? notes + "\n" : EMPTY_LOCAL);
}

export type GuideSync = { created: string[]; updated: string[] };

/**
 * Bring the three files up to date: AGENTS.local.md once, AGENTS.md whenever the
 * rendering differs, CLAUDE.md as a link when missing (a CLAUDE.md that holds
 * only the old `@AGENTS.md` import is replaced by the link; any other file or
 * link of that name is the operator's and stays).
 */
export async function syncGuide(home: string, machine: Machine = localMachine(home)): Promise<GuideSync> {
  const r: GuideSync = { created: [], updated: [] };
  const localPath = join(home, LOCAL_FILE);
  const localFile = Bun.file(localPath);
  let local: string;
  if (await localFile.exists()) {
    local = await localFile.text();
  } else {
    local = LOCAL_TEMPLATE;
    await Bun.write(localPath, local);
    r.created.push(localPath);
  }

  const guidePath = join(home, GUIDE_FILE);
  const guideFile = Bun.file(guidePath);
  const want = renderGuide(local, machine);
  const had = (await guideFile.exists()) ? await guideFile.text() : undefined;
  if (had !== want) {
    await Bun.write(guidePath, want);
    (had === undefined ? r.created : r.updated).push(guidePath);
  }

  const claudePath = join(home, CLAUDE_FILE);
  let st;
  try {
    st = await lstat(claudePath);
  } catch {
    st = undefined;
  }
  if (st?.isFile() && (await Bun.file(claudePath).text()) === "@AGENTS.md\n") {
    await unlink(claudePath); // the import form an earlier ai-space wrote
    st = undefined;
  }
  if (!st) {
    await symlink(GUIDE_FILE, claudePath);
    r.created.push(claudePath);
  }
  return r;
}
