import { describe, expect, test } from "bun:test";
import { lstat, mkdtemp, readlink, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { GUIDE_HEAD, GUIDE_TEMPLATE, LOCAL_TEMPLATE, localMachine, type Machine, machineSection, renderGuide, syncGuide } from "./guide.ts";

async function home(): Promise<string> {
  return mkdtemp(join(tmpdir(), "space-guide-"));
}

const box: Machine = { name: "gpu-box", hostname: "ip-10-0-0-7", user: "ops", home: "/srv/space" };

describe("guide", () => {
  test("renderGuide names the machine and appends the local notes without their HTML comments", () => {
    const fixed = GUIDE_HEAD + machineSection(box) + GUIDE_TEMPLATE;
    expect(renderGuide("", box)).toBe(fixed + "Nothing yet: the operator writes them in `AGENTS.local.md`.\n");
    expect(renderGuide(LOCAL_TEMPLATE, box)).toBe(renderGuide("", box));
    expect(renderGuide(LOCAL_TEMPLATE + "\n- ssh alias `box`\n<!-- private -->\n- do not rerun `nightly` by hand\n", box)).toBe(
      fixed + "- ssh alias `box`\n\n- do not rerun `nightly` by hand\n",
    );
    expect(GUIDE_HEAD.startsWith("<!-- Generated by ai-space")).toBe(true);
    // The machine section is what stops a skill written elsewhere from ssh-ing to the host it is on.
    expect(machineSection(box)).toContain("This is the space host `gpu-box` (hostname `ip-10-0-0-7`, user `ops`), and the workspace is `/srv/space`.");
    expect(machineSection(box)).toContain("never through `ssh`");
    expect(GUIDE_TEMPLATE).toContain("no hostname, IP address, ssh alias, home directory");
  });

  test("localMachine takes the space name when given and the hostname otherwise", () => {
    const m = localMachine("/w", " seoul ");
    expect(m).toMatchObject({ name: "seoul", home: "/w" });
    expect(m.hostname.length).toBeGreaterThan(0);
    expect(localMachine("/w").name).toBe(m.hostname);
    expect(localMachine("/w", "").name).toBe(m.hostname);
  });

  test("syncGuide writes the local file once, regenerates the guide, links CLAUDE.md", async () => {
    const h = await home();
    const first = await syncGuide(h, box);
    expect(first.created).toEqual([join(h, "AGENTS.local.md"), join(h, "AGENTS.md"), join(h, "CLAUDE.md")]);
    expect(first.updated).toEqual([]);
    expect(await Bun.file(join(h, "AGENTS.local.md")).text()).toBe(LOCAL_TEMPLATE);
    expect(await readlink(join(h, "CLAUDE.md"))).toBe("AGENTS.md");
    expect(await Bun.file(join(h, "CLAUDE.md")).text()).toBe(renderGuide(LOCAL_TEMPLATE, box));

    // Nothing to do the second time.
    expect(await syncGuide(h, box)).toEqual({ created: [], updated: [] });

    // The operator's notes reach the guide on the next sync; the local file is never rewritten.
    await Bun.write(join(h, "AGENTS.local.md"), "The box with the GPU.\n");
    const third = await syncGuide(h, box);
    expect(third).toEqual({ created: [], updated: [join(h, "AGENTS.md")] });
    expect(await Bun.file(join(h, "AGENTS.md")).text()).toEndWith("## Local notes\n\nThe box with the GPU.\n");
    expect(await Bun.file(join(h, "AGENTS.local.md")).text()).toBe("The box with the GPU.\n");

    // A hand edit of the generated file is undone.
    await Bun.write(join(h, "AGENTS.md"), "edited\n");
    expect((await syncGuide(h, box)).updated).toEqual([join(h, "AGENTS.md")]);
    expect(await Bun.file(join(h, "AGENTS.md")).text()).toBe(renderGuide("The box with the GPU.\n", box));

    // A renamed machine regenerates the guide too.
    expect((await syncGuide(h, { ...box, name: "gpu-box-2" })).updated).toEqual([join(h, "AGENTS.md")]);
    expect(await Bun.file(join(h, "AGENTS.md")).text()).toContain("space host `gpu-box-2`");
  });

  test("syncGuide replaces the old import-style CLAUDE.md and keeps any other", async () => {
    const old = await home();
    await Bun.write(join(old, "CLAUDE.md"), "@AGENTS.md\n");
    await Bun.write(join(old, "AGENTS.md"), "from an earlier ai-space\n");
    const r = await syncGuide(old);
    expect(r.created).toEqual([join(old, "AGENTS.local.md"), join(old, "CLAUDE.md")]);
    expect(r.updated).toEqual([join(old, "AGENTS.md")]);
    expect(await readlink(join(old, "CLAUDE.md"))).toBe("AGENTS.md");

    const mine = await home();
    await Bun.write(join(mine, "CLAUDE.md"), "my own rules\n");
    await syncGuide(mine);
    expect((await lstat(join(mine, "CLAUDE.md"))).isSymbolicLink()).toBe(false);
    expect(await Bun.file(join(mine, "CLAUDE.md")).text()).toBe("my own rules\n");

    const linked = await home();
    await symlink("/elsewhere/CLAUDE.md", join(linked, "CLAUDE.md"));
    await syncGuide(linked);
    expect(await readlink(join(linked, "CLAUDE.md"))).toBe("/elsewhere/CLAUDE.md");
  });
});
